setClass("_p__Graph")
setClass("Graph", 
	representation(
		content="character",
		storage="_p__Graph"
	)
)

setClass("SDFGraph",
	contains="Graph"
)

setMethod("initialize", "Graph",
	function(.Object, filename) {
		.Object@content = paste(readLines(filename), collapse="\n")
		.Object@storage = read_graph(filename)
		.Object
	}
)

setMethod("initialize", "SDFGraph",
	function(.Object, content) {
		.Object@content = content
		.Object@storage = parse_sdf(.Object@content)
		if (is_null(.Object@storage))
			stop("The SDF is not valid")
		.Object
	}
)

subsdf <- function(.Object, indices) {
	if (is_null(.Object@storage)) return("")
	result <- c()
	lines <- readLines(textConnection(.Object@content, open="r"))
	result <- c(result, paste(lines[1], "_SUBSDF", sep=""))
	result <- c(result, paste(lines[2], " GENERATED BY PYMCS", sep=""))
	result <- c(result, lines[3])
	result <- c(result , "place holer")
	n_atoms <- as.integer(substring(lines[4], 1, 3))
	n_bonds <- as.integer(substring(lines[4], 4, 6))
	i_atom <- 1
	for (i in indices) {
		buf <- paste(
			substring(lines[i + 4], 1, 31),
			format(i_atom, width=3),
			substring(lines[i + 4], 35),
			sep=''
			)
		i_atom <- i_atom + 1
		result <- c(result, buf)
	}
	s_bonds <- 0
	for (i in 1:n_bonds) {
		a <- as.integer(substring(lines[4 + n_atoms + i], 1, 3))
		b <- as.integer(substring(lines[4 + n_atoms + i], 4, 6))
		if (a %in% indices && b %in% indices) {
			aa <- (1:length(indices))[indices == a]
			bb <- (1:length(indices))[indices == b]
			buf <- paste(
				format(aa, width=3),
				format(bb, width=3),
				substring(lines[4 + n_atoms + i], 7),
				sep='')
			result <- c(result, buf)
			s_bonds <- s_bonds + 1
		}
	}
	result[4] <- paste(
		format(length(indices), width=3),
		format(s_bonds, width=3), 
		substring(lines[4], 7),
		sep='')
	result <- c(result, '$$$$\n')

	return(paste(result, collapse="\n"))
}

graph.from.sdffile <- function(sdffile) {
	content <- paste(readLines(file(sdffile)), collapse="\n")
	g <- new("SDFGraph", content)
	return (g)
}

mcs <- function(graph1, graph2, max_components=1, lower_bound=0, timeout=0)
{
	if (timeout) set_timeout(timeout)
	size <- max(graph1@storage, graph2@storage, max_components, lower_bound, 1)
	sub1 <- c()
	sub2 <- c()
	for (i in 1:size) sub1 <- c(sub1, get_best(1, i - 1))
	for (i in 1:size) sub2 <- c(sub2, get_best(2, i - 1))

	return(list(size=size, sub1=sub1, sub2=sub2))
}
